config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :users
  resources :projects

   root "welcome#home"

   get "about" => "welcome#about"

   get "terms" => "welcome#terms"

   get "home" => "welcome#home"

   get "faq" => "welcome#faq"

end

app/models/faq.rb
class Faq
  attr_reader :question, :answer

  def initialize(question, answer)
    @question = question
    @answer = answer
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :description, presence: true
  validate :due_date_cannot_be_in_the_past


  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "can't be in the past")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, :email, presence:true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project), notice: "Project was successfully created!"
    else
      render :new
    end   
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])

  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: "Projects was successfully deleted!"


  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to project_path(@project), notice: "Project was successfully updated!"
  end

private
def project_params
  params.require(:project).permit(
  :name
  )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    if params[:completed] == "false"
      @tasks = @tasks.where({completed: false})

    end

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :completed, :due_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "User was successfully created!"
    else
      render :new
    end  
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path, notice: "User was successfully updated!"
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: "User was successfully deleted!"
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(
    :first_name,
    :last_name,
    :email
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    @quotes = [
      ["Arnold Schwarzenegger", "\"Failure is not an option. Everyone has to succeed.\"",],
      ["Steve Jobs", "\"Your time is limited, so don't waste it living someone else's life\"",],
      ["Papa John", "\"Better Ingredients, Better Pizza\"",],
      ]

  end

  def about

  end

  def terms

  end

  def faq
    @q_and_as = [
    Faq.new("What is gCamp?", "gCamp is an awesome tool that is going to change your life. gCamp is your one stop shop to organize all your
    tasks and documents. You'll also be able to track comments that you and others make. gCamp may eventually replace
    all need for paper and pens in the entire world. Well, maybe not, but it's going to be pretty cool."),
    Faq.new("How do I join gCamp?", "Right now, gCamp is still in development.So there is not a sign-up page open to the public, yet! Your best option
    is to become super best friends with a developer. They can be found hanging around gSchool during the day and at the
    hottest clubs at night."),
    Faq.new( "When will gCamp be finished?","gCamp is a work in progress. That being said, it should be fully functional by December 2014. Functional, but our
    developers are going to continue to improve the sight for the foreseeable future. Check in daily for new features
    and new functionality. It's going to blow your mind. Organization is only (well, will only) be a click away.
    Amazing!"),]

  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GCamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href= "/home" >gCamp</a>
      </div>
    </div>
  </nav>


  <div class="container">
    <%= yield %>
  </div>

  <footer class = "navbar navbar-fixed-bottom container">
    <hr>

    <u><%= link_to "About", about_path %></u>
    |
    <u><%= link_to "Terms", terms_path %></u>
    |
    <u><%= link_to "FAQ", faq_path %></u>
    |
    <u><%= link_to "Tasks", tasks_path %></u>
    |
    <u><%= link_to "Users", users_path %></u>
    |
    <u><%= link_to "Projects", projects_path %></u>
  </footer>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, html: {class: "form-horizontal"} do |f| %>
<% if @project.errors.any? %>
<div class = "alert alert-danger col-sm-offset-1 col-sm-6">
  <div id="error_explanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

    <ul>
      <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>



<div class="form-group">
  <%= f.label :name, class:"col-sm-1 control-label" %>
  <div class="col-sm-4">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class = "form-group">
  <div class = "actions">
    <div class="col-sm-offset-1 col-sm-11">
      <%= f.submit class:  "btn btn-info" %>
      <%= link_to 'Cancel', projects_path, class: "btn btn-default" %>
    </div>
  </div>
</div>



<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<% if notice %>
  <div class= "alert alert-success">
    <p class="text-center"><%= notice %></p>
  </div>
<% end %>

<div class="page-header">
  <div class = "pull-right">
    <%= link_to "New Project", new_project_path, class: "btn btn-info" %>
  </div>
  <h1>Projects</h1>
</div>


<table class ="table">

    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to "#{project.name}", project_path(project)  %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Create Project</h1>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<% if notice %>
  <div class= "alert alert-success">
    <p class="text-center"><%= notice %></p>
  </div>
<% end %>

<div class="page-header">
  <div class = "pull-right">
    <%= link_to "edit", edit_project_path, class: "btn btn-info", id: "edit-project-action" %>
    <%= link_to "delete", project_path, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }, id: "delete-project-action" %>
  </div>
  <h1><%= @project.name %></h1>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task, html: {class: "form-horizontal" } do |f| %>
  <% if @task.errors.any? %>
  <div class = "alert alert-danger col-sm-offset-1">
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <div class = "row">
    <div class="form-group">
        <%= f.label :description, class:"col-sm-1 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class = "row">
    <div class="form-group">
      <%= f.label :due_date, class:"col-sm-1 control-label" %>
      <div class="col-sm-4">
      <%= f.date_field :due_date, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class = "row">
    <% if params[:action] == "edit" %>
    <div class = "form-group">
      <div class="col-sm-offset-1 col-sm-11">
        <%= f.check_box :completed %> completed
      </div>
    </div>
  <% end %>
  </div>

  <div class = "row">
    <div class = "form-group">
      <div class = "actions">
        <div class="col-sm-offset-1 col-sm-11">
          <%= f.submit class:  "btn btn-info" %>
          <%= link_to 'Cancel', @returnpath, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
<h1>Editing task</h1>
</div>

<% @returnpath = task_path %>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <div class = "row">
  <div class = "pull-right">
    <%= link_to "All Tasks", tasks_path %>
    | <%= link_to "Incomplete Tasks", tasks_path({completed: false})  %>
    <%= link_to "New Task", new_task_path, class: "btn btn-info" %></button>
  </div>
  </div>
  <h1>Tasks</h1>
</div>


<table class = "table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Complete</th>
      <th>Due</th>
      <th></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <% @tasks.each do |task| %>
  <tbody>

    <tr>
      <td><%= task.description %></td>
      <td><%= task.completed %></td>
      <td><%= task.due_date %></td>
      <td class= "pull-right">
        <%= link_to 'Show', task, class: "btn btn-success" %>
        <%= link_to 'Edit', edit_task_path(task), class: "btn btn-info", id: "edit-task-action" %>
        <%= link_to 'Delete', task, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<div class="page-header">
<h1>New Task</h1>
</div>
 <% @returnpath = tasks_path %>

<%= render 'form' %>

app/views/tasks/show.html.erb
<% if notice %>
  <div class = "alert alert-success">
    <p id="notice" ><%= notice %></p>
  </div>
<% end %>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
  <p> </p>
  <strong>Completed</strong>
  <%= @task.completed %>
  <p> </p>
  <strong>Due Date</strong>
  <%= @task.due_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task), id: "edit-task-action" %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for @user, html: {class: "form-horizontal" } do |f| %>
  <% if @user.errors.any? %>
  <div class = "row">
    <div class = "alert alert-danger col-sm-offset-1 col-sm-6">
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>
  <% end %>

  <div class = "row">
  <div class="form-group">
    <%= f.label :first_name, class:"col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
</div>

  <div class = "row">
  <div class="form-group">
    <%= f.label :last_name, class:"col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  </div>

  <div class = "row">
  <div class="form-group">
    <%= f.label :email, class:"col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>
  </div>

  <div class = "row">
  <div class = "form-group">
    <div class = "actions">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class:  "btn btn-info" %>
        <%= link_to 'Cancel', users_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

  <div class = "row">
  <% if params[:action] == "edit" %>
  <div class = "actions">
    <div class="col-sm-offset-2 col-sm-4">
      <div class = "form-group well well-sm">
        <div class="col-sm-offset-3 col-sm-9">
          <%= link_to 'Delete User', user_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger", id:"delete-user-action"%>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

  <% end %>

app/views/users/edit.html.erb
<div class="page-header center ">
  <h1>Edit User</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<% if notice %>
  <div class= "alert alert-success">
    <p class="text-center"><%= notice %></p>
  </div>
<% end %>



<div class="page-header">
  <div class = "pull-right">
    <%= link_to "New User", new_user_path, class: "btn btn-info" %>
  </div>
  <h1>Users</h1>
</div>


<table class = "table">
  <thead>
    <tr>
      <th>Name</th>

      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></td>
      <td><%= mail_to user.email %></td>
      <td>
        <%= link_to 'Edit', edit_user_path(user), class: "pull-right",  id: "edit-user-action" %>
      </td>
    </tr>

    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="page-header center ">
  <h1>New User</h1>
</div>


<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <div class = "pull-right">
    <%= link_to "Edit", edit_user_path(@user), class: "btn btn-info" %></button>
  </div>
  <h1> <%= @user.first_name %> <%=@user.last_name %></h1>
</div>

<dl class="dl-horizontal">
    <dt>First Name</dt>
    <dd><%= @user.first_name %></dd>
    <dt>Last Name</dt>
    <dd><%= @user.last_name %></dd>
    <dt>Email</dt>
    <dd><%= mail_to @user.email %></dd>
</dl>

app/views/welcome/about.html.erb
  <h1><big>About</big></h1>


  <div class="row">
    <div class="col-md-4">
      <%= image_tag 'about_image.png', class: "img-responsive"%>
    </div>
    <div class="col-md-8">
      <p>We are dedicated to the makers, the creators, the risk-takers. We wake up in the middle of the night and furiously write down ideas to make your online life better.</p>
      <p>When we're not hard at work, we're hard at play-we're the loud ones at the bar and we're always shutting the place down. Human communication and collaboration is what drives us, and infuses every feature of gCamp. </p>
    </div>
  </div>

app/views/welcome/faq.html.erb
  <h1><big>Frequently Asked Questions</big></h1>

  <% @q_and_as.each do |obj| %>
  <br>
  <h4> <%=obj.question%> </h4>
  <br>
  <p><%=obj.answer%></p>
  <br>
  <% end %>

app/views/welcome/home.html.erb
  <div class="jumbotron">
    <h1>gCamp</h1>
    <p>Your life organized.</p>
  </div>


  <div class="row">
    <div class="col-md-4">
      <%= image_tag 'first_image.jpg', class: "img-responsive"%>
      <p></p>
      <p></p>

      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Tasks</h3>
        </div>


        <div class="panel-body" style="height:100px">
          Grouped by projects and lists. Just the way you like 'em
        </div>
      </div>

    </div>
    <div class="col-md-4">
      <%= image_tag 'second_image.jpg', class: "img-responsive"%>
      <p></p>
      <p></p>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Documents</h3>
        </div>

        <div class="panel-body" style="height:100px">
          <ul>
            <li>Upload</li>
            <li>Comment</li>
            <li>Revise</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <%= image_tag 'third_image.jpg', class: "img-responsive"%>
      <p></p>
      <p></p>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Titles</h3>
        </div>
        <div class="panel-body" style="height:100px">
          <ul>
            <li>Comments on tasks and documents</li>
            <li>Get email notifications</li>
          </ul>
        </div>
      </div>
    </div>
  </div>


  <blockquote = "text-center">
    <% @quotes.each do |array| %>
    <p> <%=array[1]%> </p>
    <small><cite><%=array[0]%></cite></small>
    <p></p>
    <% end %>
  </blockquote>

app/views/welcome/terms.html.erb
  <h1><big>Terms</big></h1>
  <p> gCamp is not responsible for anything, unless it is positive.</p>
  <p> You may not take us to court, for anything ever.</p>